name: test and build

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'dev'
      - 'feature-*'
      - 'fix-*'
      - 'hotfix-*'
      - 'refactor-*'
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'example/**'
      - 'test/**'
      - 'build/**'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm i
      - run: npm run test